
// Get Products
export const FRANKINCENSE = 'Frankincense'
export const GERANIUM = 'Geranium'
export const AVOCADO = 'Avocado'
export const MORINGA = 'Moringa'
export const ONION_SEED_OIL = 'Onion Seed Oil'
export const ARGAN = 'Argan'
export const JOJOBA = 'Jojoba'
export const GRAPESEED = 'Grapeseed'
export const TEATREE = 'Tea Tree'
export const NEEM = 'Neem'
export const HIBISCUS = 'Hibiscus'
export const ROSEMARY = 'Rosemary'
export const HEMP = 'Hemp'
export const CUCUMBER_SEED = 'Cucumber seed'
export const CUCUMBER_GEL = 'Cucumber gel'
export const CINNAMON_POWDER = 'Cinnamon powder'
export const COCONUT = 'Coconut'
export const COCONUT_BUTTER = 'Coconut Butter'
export const NEEM_POWDER = 'Neem powder(leaf)'
export const NEEM_OIL = "Neem grade 1 oil"
export const BEESWAX = 'beeswax'
export const SWEET_ALMOND = 'Sweet Almond'
export const WHEAT_GERM = 'Wheat Germ'
export const VITAMIN_E = 'Vitamin-E'
export const MANGO_BUTTER = 'Mango Butter'
export const SHEA_BUTTER = 'Shea Butter'
export const APRICOT = 'Apricot'
export const VIRIN_OLIVE = 'Virgin Olive'
export const SAFFLOWER = 'Safflower'
export const LEMON = 'Lemon'
export const VIRGIN_COCONUT = 'Coconut'
export const COCOA_BUTTER = 'Cocoa Butter'
export const SUNFLOWER_WAX = 'Sunflower wax'
export const VEGETABLE_GLYCERINE = 'Vegetable Glycerine'
export const HONEY = 'Honey'
export const CHAMOMILE = 'Chamomile'
export const PURE_AFRICAN_SHEA_BUTTER = "Pure African Shea butter"
export const EUCALYPTUS = "Eucalyptus"
export const UNREFINED_BEESWAX = "Unrefined Beeswax"
export const UNREFINED_SHEA_BUTTER = "Unrefined Shea Butter"
export const CASTER_SUGAR = "Caster Sugar"
export const KOKUM_BUTTER = "Kokum Butter"
export const ROSE_ESSENTIALS = "Rose Essentials"
export const SANDALWOOD= "Sandalwood"
export const HELICHRYSUM = "Helichrysum"
export const ROSEHIP = "Rosehip"
export const ALOVE = "Alove"
export const LAVENDER = "Lavender"
export const KAOLIN_CLAY = "Kaolin clay"
export const DEAD_SEA_MUD = "Dead sea mud"
export const GREEN_TEA = "Green Tea extract"
export const CARROT_SEED = "Carrot Seed"
export const SAFFRON = "Saffron"
export const LEMON_GRASS = "Lemon Grass"
export const FLAVOUR_OILS = 'Essential oils based on flavour'
export const GLYCERINE = "Glycerine"
export const COCOA_POWDER = "Cocoa powder"
export const VANILLA_FRAGRANCE = "Warm Vanilla Fragrance"
export const CASHMERE = "Cashmere"
export const CHERRY_BLOSSOM_FRAGRANCE= "Cherry Blossom Fragrance"
export const MANGA_MANDARIN_FRAGRANCE = "Mango Mandarin Fragrance"
export const THYME_LEAVES = "Thyme leaves"
export const BASIL_ESSENTIALS = "Basil Essentials"
export const ROSE_FLOWER = "Rose Flower"
export const FRESH_MINT = "Fresh Mint"
export const KHUS_KHUS = "Khus khus"
export const JAU_FLOUR = "Jau Flour"
export const ORANGE_PEEL = "Orange Peel"
export const CHANA = "Chana"
export const MASOOR_DAL = "Masoor dal"
export const OATMEAL = "Oatmeal"
export const METHI = "Methi"
export const HALDI = "Haldi"
export const BADAAM = "Badaam"
export const FRESH_CUCUMBER = "Fresh Cucumber"
export const TURMERIC = "Turmeric(haldi)"
export const BESAN = "Gram Flour(besan)"
export const LEMON_EXTRACT = "Lemin extract"
export const GOAT_MILK = "Goat Milk"
export const FURTHER_CUSTOMIZATION = "Further customization available with Almond powder, Chandan powder , Saffron. Priced at Rs. 100/-"
export const RASPBERRY_SEED = "Raspberry Seed"
export const WILD_ALMONDS = "Wild Almonds"
export const CANNABIS_SATIVA = "Cannabis Sativa Seed oil"
export const WALNUT_COFFEE = "Walnut or Coffee depending on flavour"
export const CITRONELLA_OIL = "Citronella Oil"
