
// Get Products
export const FRANKINCENSE = 'Frankincense'
export const GERANIUM = 'Geranium'
export const AVOCADO = 'Avocado'
export const MORINGA = 'Moringa'
export const ARGAN = 'Argan'
export const JOJOBA = 'Jojoba'
export const GRAPESEED = 'Grapeseed'
export const TEATREE = 'Tea Tree'
export const ROSEMARY = 'Rosemary'
export const HEMP = 'Hemp'
export const CUCUMBER_SEED = 'Cucumber seed'
export const COCONUT = 'Coconut'
export const BEESWAX = 'beeswax'
export const SWEET_ALMOND = 'Sweet Almond'
export const VITAMIN_E = 'Vitamin-E'
export const MANGO_BUTTER = 'Mango Butter'
export const SHEA_BUTTER = 'Shea Butter'
export const APRICOT = 'Apricot'
export const VIRIN_OLIVE = 'Virgin Olive'
export const SAFFLOWER = 'Safflower'
export const LEMON = 'Lemon'
export const VIRGIN_COCONUT = 'Coconut'
export const COCOA_BUTTER = 'Cocoa Butter'
export const PURE_AFRICAN_SHEA_BUTTER = "Pure African Shea butter"
export const EUCALYPTUS = "Eucalyptus"
export const UNREFINED_BEESWAX = "Unrefined Beeswax"
export const CASTER_SUGAR = "Caster Sugar"
export const KOKUM_BUTTER = "Kokum Butter"
export const ROSE_ESSENTIALS = "Rose Essentials"
export const SANDALWOOD= "Sandalwood"
export const HELICHRYSUM = "Helichrysum"
export const ROSEHIP = "Rosehip"
export const ALOVE = "Alove"