

const allProducts = {
    hairMaskNormal:"Hair Mask for Normal Hair",
    hairMaskOily:"Hair Mask for Oily and Scanty Hair",
    lipBalmParent : "Lip Care",
    specialNeeds: "Special needs",
    moisturizingCreams:"Moisturizing cream",
    faceCare:"Face Care",
    allKids:"Kids special",
    antiageing:"Anti-ageing cream",
    lipbalm:"Lip Balm",
    lipbalmKids:"Lip Balm For Kids",
    lipScrubs:"Lip Scrubs",
    lipScrubsVegan:"Vegan Lip Scrubs",
    vegan:"Vegan",
    oilsAndSerums:"Oils and Serums",
    nightOil:"Night Oil",
    hairOilIntensive: "Hair Oil - Intensive Hair Care",
    hairOilAntiDandruff: "Hair Oil - Anti Dandruff",
    hairOilKids: "Hair Oil - Kids Friendly",
    faceSerum:"Skin brightening face serum",
    darkCirclesRemoval: "Under eye serum for dark circles",
    soaps: "Soaping bars",
    hydrosols:"Hydrosols and Water",
    bodyScrub:"Body Scrubbers",
    footScrub:"Foot Scrubbers",
    normalSoaps: "Nourishing Bars",
    scrubbers:"Scrubbers",
    footCare: "Foot care",
    footScrubbers:"Foot scrubber",
    bodyButter:"Body Butter",
    oils:"Oils",
    serums:"Serums",
    hairCare:"Hair Care",
    kidsSpecial:"Especially For Kids",
    kidsFriendly:"Kids cream",
    sensitiveSkin:"Cream for sensitive Skin",
    acneproneSkin:"Acne prone skin",
    roseHydrosol: "Rose Mist",
    roseWater:"Rose Arka",
    footHealer:"Foot Healer",
    kidSoap:"Kids friendly Soap",
    suitableFor:"Suitable for",
    quantity:"Quantity",
    ingredients:"Ingredients",
    keyIngredients:"Key Ingredients",
    price:"Cost",
    delivery:"Possible delivery within",
    availableinFlavours:"Available in flavours",
    howToUse:"How to use",
    precaution:"Precaution",
    allKindsOfSkin:"All Kinds of Skin",
    allKindsOfHair:"All Kinds of Hair",
    skin:"skin",
    hair:"hair",
    lipCare:"Lip care",
    sixteenYeardsOld: "Adult skin",
    mintMist: "Mint Mist"
}

export default allProducts