import allProducts from '../constants/ProductConstants'
import { ROSEMARY, TEATREE, LEMON, SWEET_ALMOND, VITAMIN_E, FRANKINCENSE, GERANIUM, GRAPESEED, SHEA_BUTTER, SAFFLOWER, HEMP, CUCUMBER_SEED, ARGAN, VIRGIN_COCONUT, MORINGA, JOJOBA, BEESWAX, MANGO_BUTTER, APRICOT, AVOCADO, VIRIN_OLIVE, COCOA_BUTTER, COCONUT, PURE_AFRICAN_SHEA_BUTTER, EUCALYPTUS, UNREFINED_BEESWAX, CASTER_SUGAR, KOKUM_BUTTER, ROSE_ESSENTIALS } from '../constants/Ingredients';
import { AGEING, DRYNESS, SUBCATEGORY_MOISTURIZING, SUBCATEGORY_KIDS, ACNE, DRYLIPS, FLAKYLIPS } from '../constants/Tags';
import { SIXTY, ONETWENTY, ROUND_FIVEGM, STICK_FIVEGM } from '../constants/Prices-Quantity';

import { LIPBALM_ONE,LIPBALM_THREE, LIPBALM_FIVE } from '../constants/ImageConstants';
import { FLAVOUR_MOISTURIZING_CREAMS, FLH, CHERRY_BLOSSOM, WINTER_BLOOM, ORANGE, ROSE_PETALS, FLAVOUR_LIP_BALMS, FLAVOUR_LIP_BALMS_KIDS, FLAVOUR_LIP_SCRUBS, VEGAN_LIP_SCRUBS } from '../constants/variants';

const allItems = [
{
  "id": 1,
  "name": allProducts.moisturizingCreams,
  "type":allProducts.skin,
  "price": 250,
  "salePrice": 250,
  "discount": 0,
  "pictures": ["/assets/images/moisturizingCreams/frenchLavender_1.jpg", "/assets/images/moisturizingCreams/frenchLavender_2.jpg", "/assets/images/moisturizingCreams/orange_big.jpg", "/assets/images/moisturizingCreams/rose_big.jpg"],
  "shortDetails": "Moisturizing cream for daily use",
  "description": "Daily moisturizing is vital for a healthy skin. Leaving skin without a moisturizer means compromising the protective skin barrier. Kurinjini brings to you a Shea, Mango butter based moisturizer that also has the anti-oxidant properties brought by Vitamin-E. Along with these, we have also added Jojoba and Sweet Almond oils provide that extra nourishment to the skin. We also take customized orders for your specific requirement on fragrance.",
  "stock": 10,
  "new": true,
  "sale": false,
  "quantity":"60 ml",
  "category": allProducts.faceCare,
  "subCategory":[SUBCATEGORY_MOISTURIZING, SUBCATEGORY_KIDS],
  "ingredients": [JOJOBA, SWEET_ALMOND, VITAMIN_E, MANGO_BUTTER, TEATREE, ROSEMARY,COCONUT,VIRIN_OLIVE, BEESWAX],
  "size": [SIXTY, ONETWENTY],
  "tags": [DRYNESS],
  "rating": 4,
  "flavours":[FLH, CHERRY_BLOSSOM, WINTER_BLOOM, ORANGE, ROSE_PETALS],
  "variants": FLAVOUR_MOISTURIZING_CREAMS,
  "goodFor":[allProducts.allKindsOfSkin],
  "precaution":"All our moisturizing creams should be kept away from sunlight as it may lose its consistency"
},
{
  "id": 2,
  "name": "Immortal",
  "type":allProducts.skin,
  "price": 300.00,
  "salePrice": 300.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/FaceCare/SpecialNeeds/Immortal_two.jpg", "/assets/images/kurinjini-images/FaceCare/SpecialNeeds/Immortal_three.jpg"],
  "shortDetails": "Immortal is our most popular face cream.",
  "description": "Cellular regeneration is the key to a youthful skin, and essential oils provide a way of doing this which is far more pleasant and safe than methods involving synthetic chemicals.Immortal is not only an anti-ageing cream but it also helps fight hyperpigmentation. It has ingredients that stimualte skin cells into reproducing at a quicker rate, thus reducing the time-lag between new skin growth and the elimination of old cells. Immortal has essentials that are considered to be anti-wrinkle, act as a skin tightening agent, helping in reducing dark spots and blemishes. It is high in Vitamin-A and Vitamin-E oil that prevents formation of free radicals that are scientifically proven to be one of the reasons of pre-mature ageing. Immortal is our most popular face cream. Lot of people have given a great feedback on this cream.",
  "stock": 10,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [FRANKINCENSE, GERANIUM, AVOCADO, MORINGA, ARGAN, JOJOBA, GRAPESEED, TEATREE, ROSEMARY, HEMP, CUCUMBER_SEED,  COCONUT, BEESWAX, SWEET_ALMOND, VITAMIN_E, MANGO_BUTTER, PURE_AFRICAN_SHEA_BUTTER, APRICOT],
  "size": ["60ml", "120ml"],
  "tags": [AGEING],
  "rating": 5,
  "variants": [],
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.moisturizingCreams]
},
{
  "id": 3,
  "name": "Fluffy",
  "type":allProducts.skin,
  "price": 300.00,
  "salePrice": 300.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/FaceCare/SpecialNeeds/fluffy_two.jpg","/assets/images/kurinjini-images/FaceCare/SpecialNeeds/fluffy_one.jpg"],
  "shortDetails": "A cream for Kids",
  "description": "Very mild cream with combination of kids skin friendly oil like Jojoba, Argan and Almond. The essential oils fight infection and promote healing thus providing parents some relaxation in caring for their child.",
  "stock": 10,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [JOJOBA, VITAMIN_E, SWEET_ALMOND, ARGAN, AVOCADO, VIRGIN_COCONUT, VIRIN_OLIVE, COCOA_BUTTER, MANGO_BUTTER, SHEA_BUTTER],
  "size": ["60ml", "120ml"],
  "tags": [DRYNESS],
  "rating": 3,
  "variants": [],
  "goodFor":[allProducts.kidsSpecial],
  "subCategory":[allProducts.moisturizingCreams]
},
{
  "id": 4,
  "name": "Pacific",
  "type":allProducts.skin,
  "price": 300.00,
  "salePrice": 300.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/FaceCare/SpecialNeeds/pacific_big.jpg","/assets/images/kurinjini-images/FaceCare/SpecialNeeds/pacific_small.jpg"],
  "shortDetails": "A cream for sensitive skin",
  "description": "Pacific has speciality of soothing sensitive skin. It has ingredients like Rosemary, Tea tree and safflower oil that refresh oily skin without causing excess dryness. Tea tree and Rosemary are considered to be a natural antiseptic and has astringent properties. It is effective in lightening scars, soothing pimples apart from being anti-blemish, anti-microbial agents.",
  "stock": 6,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [ROSEMARY, TEATREE, EUCALYPTUS, SAFFLOWER, LEMON, HEMP, CUCUMBER_SEED, ARGAN, VIRGIN_COCONUT, SWEET_ALMOND, VITAMIN_E, FRANKINCENSE, GERANIUM, MORINGA, JOJOBA, GRAPESEED, BEESWAX, MANGO_BUTTER, PURE_AFRICAN_SHEA_BUTTER, APRICOT],
  "size": ["60ml", "120ml"],
  "tags": [ACNE],
  "rating": 3,
  "variants": [],
  "goodFor":[allProducts.acneproneSkin, allProducts.allKindsOfSkin],
  "subCategory":[allProducts.moisturizingCreams]
},
{
  "id": 5,
  "name": "Lip Balms",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": [LIPBALM_ONE,LIPBALM_THREE, LIPBALM_FIVE],
  "shortDetails": "Lip care for all seasons",
  "description": "Lip balms are made of cocoa butter which is a natural, meltable oil extracted from the cocoa bean. Cocoa butter is great for naturally healing dry, sensitive skin. it has a mild fragrance, a smooth texture and is ultra-hydrating. Unrefined beeswax, consisting of naturally produced vitamins makes it healthier and prevents from further dryness and chapping of the lips.",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [UNREFINED_BEESWAX, COCOA_BUTTER, JOJOBA, SWEET_ALMOND, VITAMIN_E, AVOCADO],
  "size": [ROUND_FIVEGM, STICK_FIVEGM],
  "tags": [DRYLIPS],
  "rating": 4,
  "variants": FLAVOUR_LIP_BALMS,
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipbalm]
},
{
  "id": 6,
  "name": "Lip Balms for kids",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": [LIPBALM_ONE,LIPBALM_THREE, LIPBALM_FIVE],
  "shortDetails": "Lip care especially for kids",
  "description": "Give your kids the freedom from dry and chapped lips. Strawberry and Chocolate flavoured lip balm made primarily out of Cocoa Butter, Avocado oil & Sweet Almond oil. The added oils provide the necessary hydration and softness.",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.lipCare,
  "ingredients": [UNREFINED_BEESWAX, COCOA_BUTTER, SWEET_ALMOND, VITAMIN_E, AVOCADO],
  "size": [ROUND_FIVEGM, STICK_FIVEGM],
  "tags": [DRYLIPS],
  "rating": 4,
  "variants": FLAVOUR_LIP_BALMS_KIDS,
  "goodFor":[allProducts.kidsSpecial, allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipbalm]
},
{
  "id": 7,
  "name": "Lip Scrubs",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/LipCare/lipScrub4_small.jpg"],
  "shortDetails": "Lip scrub that peels off dry and flaky skin",
  "description": "Sugar-based exfoliator that peels off dry and flaky skin from your lips along with providing the needed hydration and nourishment. It has a sweet sugary flavour through caster sugar blended with raw unbleached beeswax and Cocoa butter. The nourishing oils used are Sweet Almond, Jojoba and Vitamin-E.",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.lipCare,
  "ingredients": [CASTER_SUGAR, UNREFINED_BEESWAX, COCOA_BUTTER, SWEET_ALMOND, VITAMIN_E],
  "size": [ROUND_FIVEGM],
  "tags": [DRYLIPS, FLAKYLIPS],
  "rating": 4,
  "variants": FLAVOUR_LIP_SCRUBS,
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipScrubs],
  "howToUse":"Rub gently on the lips and after some continuous rounds of rubbing, wipe off with towel or rinse with water"
},
{
  "id": 8,
  "name": "Vegan Lip Scrubs",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/LipCare/lipScrub4_small.jpg"],
  "shortDetails": "Lip scrub that peels off dry and flaky skin",
  "description": "Natural fragrance and colour derived from powder like rose, chocolate strawberry powder that is made at home. Along with keeping skin soft and smooth, it is also rich in Vitamin-C and other anti-oxidants that strengthens skin cells and tissues. Other ingredients like Kokum butter has properties that rejuvenates damaged skin cells which makes it ideal for lip scrub. Kokum butter has properties that rejuvenates damaged skin cells which makes it ideal for lip scrub. <b> Doesn’t contain any beeswax</b>",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.lipCare,
  "ingredients": [KOKUM_BUTTER, COCOA_BUTTER, ROSE_ESSENTIALS],
  "size": [ROUND_FIVEGM],
  "tags": [DRYLIPS, FLAKYLIPS],
  "rating": 4,
  "variants": VEGAN_LIP_SCRUBS,
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipScrubsVegan, allProducts.vegan],
  "howToUse":"Rub gently on the lips and after some continuous rounds of rubbing, wipe off with towel or rinse with water"
}
]
export default allItems