import allProducts from '../constants/ProductConstants'
import { ROSEMARY, TEATREE, LEMON, SWEET_ALMOND, VITAMIN_E, FRANKINCENSE, GERANIUM, GRAPESEED, SHEA_BUTTER, SAFFLOWER, HEMP, CUCUMBER_SEED, ARGAN, VIRGIN_COCONUT, MORINGA, JOJOBA, BEESWAX, MANGO_BUTTER, APRICOT, AVOCADO, VIRIN_OLIVE, COCOA_BUTTER, COCONUT, PURE_AFRICAN_SHEA_BUTTER, EUCALYPTUS, UNREFINED_BEESWAX, CASTER_SUGAR, KOKUM_BUTTER, ROSE_ESSENTIALS, SANDALWOOD, HELICHRYSUM, ROSEHIP, ALOVE, LAVENDER, CARROT_SEED, SAFFRON, LEMON_GRASS, NEEM, HIBISCUS } from '../constants/Ingredients';
import { AGEING, DRYNESS, SUBCATEGORY_MOISTURIZING, SUBCATEGORY_KIDS, ACNE, DRYLIPS, FLAKYLIPS, DULLSKIN, DARK_CIRCLES, BLEMISHES, PIGMENTATION, DANDRUFF, SPLIT_ENDS, HAIR_FALL } from '../constants/Tags';
import { SIXTY, ONETWENTY, ROUND_FIVEGM, STICK_FIVEGM, TWENTY, FIFTEEN, EIGHTY } from '../constants/Prices-Quantity';
import React from 'react'
import { LIPBALM_ONE,LIPBALM_THREE, LIPBALM_FIVE } from '../constants/ImageConstants';
import { FLAVOUR_MOISTURIZING_CREAMS, FLH, CHERRY_BLOSSOM, WINTER_BLOOM, ORANGE, ROSE_PETALS, FLAVOUR_LIP_BALMS, FLAVOUR_LIP_BALMS_KIDS, FLAVOUR_LIP_SCRUBS, VEGAN_LIP_SCRUBS, VARIANTS_RENAISSANCE } from '../constants/variants';

const allItems = [
{
  "id": 1,
  "name": allProducts.moisturizingCreams,
  "type":allProducts.skin,
  "price": 250,
  "salePrice": 250,
  "discount": 0,
  "pictures": ["/assets/images/moisturizingCreams/frenchLavender_1.jpg", "/assets/images/moisturizingCreams/frenchLavender_2.jpg", "/assets/images/moisturizingCreams/orange_big.jpg", "/assets/images/moisturizingCreams/rose_big.jpg"],
  "shortDetails": "Moisturizing cream for daily use",
  "description": "Daily moisturizing is vital for a healthy skin. Leaving skin without a moisturizer means compromising the protective skin barrier. Kurinjini brings to you a Shea, Mango butter based moisturizer that also has the anti-oxidant properties brought by Vitamin-E. Along with these, we have also added Jojoba and Sweet Almond oils provide that extra nourishment to the skin. We also take customized orders for your specific requirement on fragrance.",
  "stock": 10,
  "new": true,
  "sale": false,
  "quantity":"60 ml",
  "category": allProducts.faceCare,
  "subCategory":[SUBCATEGORY_MOISTURIZING, SUBCATEGORY_KIDS],
  "ingredients": [JOJOBA, SWEET_ALMOND, VITAMIN_E, MANGO_BUTTER, TEATREE, ROSEMARY,COCONUT,VIRIN_OLIVE, BEESWAX],
  "size": [SIXTY, ONETWENTY],
  "tags": [DRYNESS],
  "rating": 4,
  "flavours":[FLH, CHERRY_BLOSSOM, WINTER_BLOOM, ORANGE, ROSE_PETALS],
  "variants": FLAVOUR_MOISTURIZING_CREAMS,
  "goodFor":[allProducts.allKindsOfSkin],
  "precaution":"All our moisturizing creams should be kept away from sunlight as it may lose its consistency"
},
{
  "id": 2,
  "name": "Immortal",
  "type":allProducts.skin,
  "price": 300.00,
  "salePrice": 300.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/FaceCare/SpecialNeeds/Immortal_two.jpg", "/assets/images/kurinjini-images/FaceCare/SpecialNeeds/Immortal_three.jpg"],
  "shortDetails": "Immortal is our most popular face cream.",
  "description": "Cellular regeneration is the key to a youthful skin, and essential oils provide a way of doing this which is far more pleasant and safe than methods involving synthetic chemicals.Immortal is not only an anti-ageing cream but it also helps fight hyperpigmentation. It has ingredients that stimualte skin cells into reproducing at a quicker rate, thus reducing the time-lag between new skin growth and the elimination of old cells. Immortal has essentials that are considered to be anti-wrinkle, act as a skin tightening agent, helping in reducing dark spots and blemishes. It is high in Vitamin-A and Vitamin-E oil that prevents formation of free radicals that are scientifically proven to be one of the reasons of pre-mature ageing. Immortal is our most popular face cream. Lot of people have given a great feedback on this cream.",
  "stock": 10,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [FRANKINCENSE, GERANIUM, AVOCADO, MORINGA, ARGAN, JOJOBA, GRAPESEED, TEATREE, ROSEMARY, HEMP, CUCUMBER_SEED,  COCONUT, BEESWAX, SWEET_ALMOND, VITAMIN_E, MANGO_BUTTER, PURE_AFRICAN_SHEA_BUTTER, APRICOT],
  "size": ["60ml", "120ml"],
  "tags": [AGEING],
  "rating": 5,
  "variants": [],
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.moisturizingCreams]
},
{
  "id": 3,
  "name": "Fluffy",
  "type":allProducts.skin,
  "price": 300.00,
  "salePrice": 300.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/FaceCare/SpecialNeeds/fluffy_two.jpg","/assets/images/kurinjini-images/FaceCare/SpecialNeeds/fluffy_one.jpg"],
  "shortDetails": "A cream for Kids",
  "description": "Very mild cream with combination of kids skin friendly oil like Jojoba, Argan and Almond. The essential oils fight infection and promote healing thus providing parents some relaxation in caring for their child.",
  "stock": 10,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [JOJOBA, VITAMIN_E, SWEET_ALMOND, ARGAN, AVOCADO, VIRGIN_COCONUT, VIRIN_OLIVE, COCOA_BUTTER, MANGO_BUTTER, SHEA_BUTTER],
  "size": ["60ml", "120ml"],
  "tags": [DRYNESS],
  "rating": 3,
  "variants": [],
  "goodFor":[allProducts.kidsSpecial],
  "subCategory":[allProducts.moisturizingCreams]
},
{
  "id": 4,
  "name": "Pacific",
  "type":allProducts.skin,
  "price": 300.00,
  "salePrice": 300.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/FaceCare/SpecialNeeds/pacific_big.jpg","/assets/images/kurinjini-images/FaceCare/SpecialNeeds/pacific_small.jpg"],
  "shortDetails": "A cream for sensitive skin",
  "description": "Pacific has speciality of soothing sensitive skin. It has ingredients like Rosemary, Tea tree and safflower oil that refresh oily skin without causing excess dryness. Tea tree and Rosemary are considered to be a natural antiseptic and has astringent properties. It is effective in lightening scars, soothing pimples apart from being anti-blemish, anti-microbial agents.",
  "stock": 6,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [ROSEMARY, TEATREE, EUCALYPTUS, SAFFLOWER, LEMON, HEMP, CUCUMBER_SEED, ARGAN, VIRGIN_COCONUT, SWEET_ALMOND, VITAMIN_E, FRANKINCENSE, GERANIUM, MORINGA, JOJOBA, GRAPESEED, BEESWAX, MANGO_BUTTER, PURE_AFRICAN_SHEA_BUTTER, APRICOT],
  "size": ["60ml", "120ml"],
  "tags": [ACNE],
  "rating": 3,
  "variants": [],
  "goodFor":[allProducts.acneproneSkin, allProducts.allKindsOfSkin],
  "subCategory":[allProducts.moisturizingCreams]
},
{
  "id": 5,
  "name": "Lip Balms",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": [LIPBALM_ONE,LIPBALM_THREE, LIPBALM_FIVE],
  "shortDetails": "Lip care for all seasons",
  "description": "Lip balms are made of cocoa butter which is a natural, meltable oil extracted from the cocoa bean. Cocoa butter is great for naturally healing dry, sensitive skin. it has a mild fragrance, a smooth texture and is ultra-hydrating. Unrefined beeswax, consisting of naturally produced vitamins makes it healthier and prevents from further dryness and chapping of the lips.",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.faceCare,
  "ingredients": [UNREFINED_BEESWAX, COCOA_BUTTER, JOJOBA, SWEET_ALMOND, VITAMIN_E, AVOCADO],
  "size": [ROUND_FIVEGM, STICK_FIVEGM],
  "tags": [DRYLIPS],
  "rating": 4,
  "variants": FLAVOUR_LIP_BALMS,
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipbalm]
},
{
  "id": 6,
  "name": "Lip Balms for kids",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": [LIPBALM_ONE,LIPBALM_THREE, LIPBALM_FIVE],
  "shortDetails": "Lip care especially for kids",
  "description": "Give your kids the freedom from dry and chapped lips. Strawberry and Chocolate flavoured lip balm made primarily out of Cocoa Butter, Avocado oil & Sweet Almond oil. The added oils provide the necessary hydration and softness.",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.lipCare,
  "ingredients": [UNREFINED_BEESWAX, COCOA_BUTTER, SWEET_ALMOND, VITAMIN_E, AVOCADO],
  "size": [ROUND_FIVEGM, STICK_FIVEGM],
  "tags": [DRYLIPS],
  "rating": 4,
  "variants": FLAVOUR_LIP_BALMS_KIDS,
  "goodFor":[allProducts.kidsSpecial, allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipbalm]
},
{
  "id": 7,
  "name": "Lip Scrubs",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/LipCare/lipScrub4_small.jpg"],
  "shortDetails": "Lip scrub that peels off dry and flaky skin",
  "description": "Sugar-based exfoliator that peels off dry and flaky skin from your lips along with providing the needed hydration and nourishment. It has a sweet sugary flavour through caster sugar blended with raw unbleached beeswax and Cocoa butter. The nourishing oils used are Sweet Almond, Jojoba and Vitamin-E.",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.lipCare,
  "ingredients": [CASTER_SUGAR, UNREFINED_BEESWAX, COCOA_BUTTER, SWEET_ALMOND, VITAMIN_E],
  "size": [ROUND_FIVEGM],
  "tags": [DRYLIPS, FLAKYLIPS],
  "rating": 4,
  "variants": FLAVOUR_LIP_SCRUBS,
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipScrubs],
  "howToUse":"Rub gently on the lips and after some continuous rounds of rubbing, wipe off with towel or rinse with water"
},
{
  "id": 8,
  "name": "Vegan Lip Scrubs",
  "type":allProducts.skin,
  "price": 100.00,
  "salePrice": 100.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/LipCare/lipScrub4_small.jpg"],
  "shortDetails": "Lip scrub that peels off dry and flaky skin",
  "description": "Natural fragrance and colour derived from powder like rose, chocolate strawberry powder that is made at home. Along with keeping skin soft and smooth, it is also rich in Vitamin-C and other anti-oxidants that strengthens skin cells and tissues. Other ingredients like Kokum butter has properties that rejuvenates damaged skin cells which makes it ideal for lip scrub. Kokum butter has properties that rejuvenates damaged skin cells which makes it ideal for lip scrub. <b> Doesn’t contain any beeswax</b>",
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.lipCare,
  "ingredients": [KOKUM_BUTTER, COCOA_BUTTER, ROSE_ESSENTIALS],
  "size": [ROUND_FIVEGM],
  "tags": [DRYLIPS, FLAKYLIPS],
  "rating": 4,
  "variants": VEGAN_LIP_SCRUBS,
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.lipScrubsVegan, allProducts.vegan],
  "howToUse":"Rub gently on the lips and after some continuous rounds of rubbing, wipe off with towel or rinse with water"
},
{
  "id": 9,
  "name": "Sparkle",
  "type":allProducts.skin,
  "price": 350.00,
  "salePrice": 350.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/Oils/Serums/sparkle_big.jpg", "/assets/images/kurinjini-images/Oils/Serums/sparkleTwo_big.jpg"],
  "shortDetails": "Skin brightening serum",
  "description": "As the name suggests, it's a silicone free skin brightening overnight serum that absorbs quickly in the skin and gives a radiating effect over a period of time. Pores are tiny openings in the skin that release oil and sweat. When pores are clogged, it can result in blackheads or acne. This serum aims to unclog the pores. It also has Helichrysum essential oil that helps smooth both skin tone and texture, reduces the appearance of fine lines, and its emollient properties help keep skin hydrated. Helichrysum is also known to be beneficial for treating sunburns. Along with it is also added few drops of Mysore Sandalwood oil that acts as an antiseptic and anti-inflammatory agent too apart from being a brightening agent. Also added is Rosehip that tightens the pores and brightens your skin. Mixed with other essentials and carrier oils, this brightening skin serum is good for all kinds of skin.",
  "stock": 5,
  "new": false,
  "sale": false,
  "category": allProducts.oilsAndSerums,
  "ingredients": [SANDALWOOD, HELICHRYSUM, ROSEHIP, FRANKINCENSE, VITAMIN_E, JOJOBA, SWEET_ALMOND, HEMP, AVOCADO, MORINGA, ALOVE],
  "size": [TWENTY],
  "tags": [DULLSKIN],
  "rating": 5,
  "variants": [],
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.faceSerum],
  "howToUse":"It's a night application cream. Take a small quantity on your finger tip and apply gently after a face wash on your face."
},
{
  "id": 10,
  "name": "Moonstone",
  "type":allProducts.skin,
  "price": 350.00,
  "salePrice": 350.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/Oils/Serums/moonstone_big.jpg"],
  "shortDetails": "An under eye serum to get rid of dark circles",
  "description": "Moonstone is an under eye serum, an attempt from us to come up with something that can reduce the dark circles. Apart from some of the ingredients already present in “Sparkle”, there is also cucumber seed and carrot seed oil that reduces stress and tiredness from the eyes, keeping it cool. With its high content of vitamin C, beta-carotene and manganese, cucumber oil can stimulate collagen production, too. Collagen is the protein that provides the structure of your skin. It helps boosting your body’s natural collagen synthesis without having to rely on chemicals and synthetic ingredients. Carrot seed essential oil, a skin lightening agent, improves moisture retention, reduce the look of tired skin, and help nourish dry areas. Another essential added is Lavender, that helps enhance blood circulation and a natural healer along with reducing stress and anxiety. All these added with carrier oils forms this natural healer Moonstone.",
  "stock": 5,
  "new": false,
  "sale": false,
  "category": allProducts.oilsAndSerums,
  "ingredients": [SANDALWOOD, HELICHRYSUM, GERANIUM, LAVENDER, CARROT_SEED, CUCUMBER_SEED, ROSEHIP, VITAMIN_E, JOJOBA, SWEET_ALMOND, HEMP, ALOVE],
  "size": [TWENTY],
  "tags": [DARK_CIRCLES],
  "rating": 4,
  "variants": [],
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.darkCirclesRemoval],
  "howToUse":"It's a night application cream. Take a small quantity on your finger tip and massage gently under your eyes so that it improves blood circulation."
},
{
  "id": 11,
  "name": "Renaissance",
  "type":allProducts.skin,
  "price": 200.00,
  "salePrice": 200.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/Oils/hairandface/renaissance_1.jpg", "/assets/images/kurinjini-images/Oils/hairandface/renaissance_2.jpg"],
  "shortDetails": "Extra-hydrating night application oil",
  "description": <p>Extra-hydrating night application oil that has quick absorption quality. Its a combination of oils and essential oils having properties of skin brightening, removal of hyper-pigmentation, even removing blemishes. The basic component is Vitamin-E oil and along with carrier oils as Sweet Almond oil.
  <br/><br/>
  Additionally we also support specific customized needs:
  <ul>
    <li>For glowing skin </li>
    <li> Anti-ageing </li>
    <li> Acne control </li>
  </ul>  
  <br/>
  <b><i> it is available in more convenient to use glass droppers.</i></b></p>,
  "stock": 20,
  "new": false,
  "sale": false,
  "category": allProducts.oilsAndSerums,
  "ingredients": [SAFFRON, ARGAN, MORINGA, TEATREE, GERANIUM, ROSEMARY, JOJOBA, GRAPESEED, CUCUMBER_SEED, HEMP, AVOCADO, FRANKINCENSE, LEMON_GRASS, COCONUT],
  "size": [FIFTEEN],
  "tags": [DARK_CIRCLES, BLEMISHES, PIGMENTATION, ACNE],
  "rating": 5,
  "variants": VARIANTS_RENAISSANCE,
  "goodFor":[allProducts.allKindsOfSkin],
  "subCategory":[allProducts.nightOil],
  "howToUse":"Apply after a face wash during night before going to bed."
},
{
  "id": 12,
  "name": "Resurgence - Intensive hair oil treatment",
  "type":allProducts.hair,
  "price": 350.00,
  "salePrice": 350.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/Oils/hairandface/hair.jpg"],
  "shortDetails": "An intenstive hair oil treatment",
  "description": <p> Our hair is just as sensitive as our skin. The basic substance of hair is keratin, a strong protein. When we lose our hair as each one comes to the end, a new hair should grow in its place. This should happen instantaneously but because of our lifestyle and synthetic chemicals that we apply with shampoo or conditioners, the time between a hair getting lost and new one coming up can extend so that our hair begins to thin. “Resurgence” is an intense hair treatment oil. It consists of Argan, Grapeseed essential oils that consists of Vitamin-E, a natural anti-oxidant that nourishes dry damaged hair, repairs and rejuvenates, thereby protecting it and giving it the needed shine. Hemp oil is a great oil for scalp and helps grow hair faster, thicker and longer. Avocado oil present acts as a carrier oil stimulating the blood flow and unclog blocked follicles.</p>,
  "stock": 10,
  "new": false,
  "sale": false,
  "category": allProducts.oilsAndSerums,
  "ingredients": [ARGAN, MORINGA, GRAPESEED, JOJOBA, HEMP, FRANKINCENSE, SWEET_ALMOND, VITAMIN_E],
  "size": [EIGHTY],
  "tags": [DANDRUFF, SPLIT_ENDS, HAIR_FALL],
  "rating": 5,
  "variants": [],
  "goodFor":[allProducts.allKindsOfHair],
  "subCategory":[allProducts.hairOilIntensive, allProducts.hairOilAntiDandruff],
  "howToUse":"Direct application on your hair and scalp"
},
{
  "id": 13,
  "name": "Resurgence - Anti-Dandruff treatment",
  "type":allProducts.hair,
  "price": 350.00,
  "salePrice": 350.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/Oils/hairandface/hair.jpg"],
  "shortDetails": "Anti-dandruff treatment",
  "description": <p> The little white flakes scattered on shoulders shout out loudly that someone’s head and hair are in bad condition. But with essential oils, you can get to the root of the problem and get rid of this once and for all. Essential Oils like Rosemary, Tea Tree and oils like Jojoba, Hibiscus and Neem are effective in treating dandruff and split ends.</p>,
  "stock": 10,
  "new": false,
  "sale": false,
  "category": allProducts.oilsAndSerums,
  "ingredients": [ARGAN, TEATREE, NEEM, HIBISCUS, MORINGA, ROSEMARY, GRAPESEED, AVOCADO, JOJOBA, HEMP, FRANKINCENSE],
  "size": [EIGHTY],
  "tags": [DANDRUFF],
  "rating": 5,
  "variants": [],
  "goodFor":[allProducts.allKindsOfHair],
  "subCategory":[allProducts.hairOilIntensive, allProducts.hairOilAntiDandruff],
  "howToUse":"Direct application on your hair and scalp"
},
{
  "id": 14,
  "name": "Resurgence - Hair treatment for kids",
  "type":allProducts.hair,
  "price": 300.00,
  "salePrice": 300.00,
  "discount": 0,
  "pictures": ["/assets/images/kurinjini-images/Oils/hairandface/hair.jpg"],
  "shortDetails": "Hair oil for your kids",
  "description": <p>Kids hair oil is gentle in nature and consist of Argan and Jojoba mixed with most effective natural cold pressed oils like Coconut and Virgin Olive. It helps keep small ones' hair hydrated & moisturized while it also serves to nourish & soften the scalp. </p>,
  "stock": 10,
  "new": false,
  "sale": false,
  "category": allProducts.oilsAndSerums,
  "ingredients": [ARGAN, JOJOBA, HEMP, SWEET_ALMOND, AVOCADO, VIRIN_OLIVE, COCONUT],
  "size": [EIGHTY],
  "tags": [DANDRUFF, HAIR_FALL],
  "rating": 5,
  "variants": [],
  "goodFor":[allProducts.kidsSpecial],
  "subCategory":[allProducts.hairOilKids],
  "howToUse":"Direct application on your hair and scalp"
}
]
export default allItems